import { useState, useCallback } from 'react';

export const useCart = () => {
  // Lấy dữ liệu giỏ hàng từ bộ nhớ trình duyệt (nếu có)
  const [cartItems, setCartItems] = useState(() => {
    const saved = localStorage.getItem('problem-bank-cart');
    return saved ? JSON.parse(saved) : [];
  });

  // Thêm câu hỏi vào giỏ
  const addToCart = useCallback((problem) => {
    setCartItems(prev => {
      // Kiểm tra xem câu hỏi đã có trong giỏ chưa để tránh thêm trùng
      if (prev.find(p => p.id === problem.id)) return prev;
      
      const newCart = [...prev, problem];
      localStorage.setItem('problem-bank-cart', JSON.stringify(newCart));
      return newCart;
    });
  }, []);

  // Xóa câu hỏi khỏi giỏ
  const removeFromCart = useCallback((problemId) => {
    setCartItems(prev => {
      const newCart = prev.filter(p => p.id !== problemId);
      localStorage.setItem('problem-bank-cart', JSON.stringify(newCart));
      return newCart;
    });
  }, []);

  // Làm sạch giỏ hàng
  const clearCart = useCallback(() => {
    setCartItems([]);
    localStorage.removeItem('problem-bank-cart');
  }, []);

  // Xuất file Đề thi
  const exportCart = useCallback((options = {}) => {
    const {
      includeSolutions = true,
      randomize = false,
      addTitle = true
    } = options;

    let content = '';
    
    // Thêm phần khai báo đầu file LaTeX (Preamble)
    if (addTitle) {
      content += '\\documentclass{article}\n';
      content += '\\usepackage[utf8]{inputenc}\n';
      content += '\\title{Bài Tập Toán Chuyên}\n';
      content += '\\author{Generated by Problem Bank}\n';
      content += '\\begin{document}\n\n';
      content += '\\maketitle\n\\newpage\n\n';
    }

    // Đảo lộn thứ tự câu hỏi (nếu Thầy muốn xáo đề)
    let itemsToExport = [...cartItems];
    if (randomize) {
      itemsToExport = itemsToExport.sort(() => Math.random() - 0.5);
    }

    // Ghép nội dung từng bài toán
    itemsToExport.forEach(problem => {
      content += '\\begin{bt}\n';
      content += problem.statement + '\n';
      if (includeSolutions && problem.solution) {
        content += '\\loigiai{\n' + problem.solution + '\n}\n';
      }
      content += '\\end{bt}\n\n';
    });

    if (addTitle) {
      content += '\\end{document}\n';
    }

    // Tải file xuống
    const element = document.createElement('a');
    element.setAttribute(
      'href',
      'data:text/plain;charset=utf-8,' + encodeURIComponent(content)
    );
    element.setAttribute('download', 'exam_' + Date.now() + '.tex');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [cartItems]);

  return {
    cartItems,
    addToCart,
    removeFromCart,
    clearCart,
    exportCart,
    cartCount: cartItems.length
  };
};